"""Initial migration

Revision ID: 8eb452de0f0b
Revises: 
Create Date: 2026-02-07 22:53:03.728412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8eb452de0f0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_plans', 'free_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='10. 自由記述欄',
               existing_comment='10. è‡ªç”±è¨˜è¿°æ¬„',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_plans', 'free_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='10. è‡ªç”±è¨˜è¿°æ¬„',
               existing_comment='10. 自由記述欄',
               existing_nullable=True)
    # ### end Alembic commands ###
